service: youtube-music-backend

app: youtube-music-backend
# org: devnok

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev
  # vpc:
  #   securityGroupIds:
  #     - sg-d0be64b5
  #   subnetIds:
  #     - subnet-f7ff7c8c
  #     - subnet-525d671e
  #     - subnet-9eba6cf5

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
