version: '3'

services:
  db:
    restart: always
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: youtubemusicpw
      MYSQL_DATABASE: youtubemusic
    ports:
      - 3306:3306
    volumes:
      - ./docker/data:/var/lib/mysql
